*Anna Aiuppa;
*4/12/19;
*Longitudinal and Multilevel Data Analysis;
%let pathname=C:\Users\annaa\Documents\LongitudinalMultilevelDataAnalysis\Data\;
*suicide.csv is a data set with 27,820 observations with 12 variables;
proc import datafile="&pathname.suicide.csv" DBMS=CSV replace out=suicide;
run; 
title 'Check variable names';
proc contents data=suicide;
run;
*Print first 20 observations of the data set;
title "Subset of the data";
proc print data=suicide(obs=20);
run;

**Descriptive Statistics: ODDS, LOG ODDS (LOGITS);
PROC SORT DATA=suicide; 
BY year country sex; 
RUN;
*this is going to show means of suicide numbers for age groups.. ;
*as in, the maximum # given will be for the age category with the most suicides   ;
PROC MEANS DATA=suicide;
VAR suicides_no;
BY year country;
OUTPUT OUT=suicide_binary_means; RUN;
*this will give means data for countries without separating by year;
PROC MEANS DATA=suicide;
VAR suicides_no;
BY country sex;
OUTPUT OUT=count_sex_binary_means; RUN;
*kind of sad - it looks like men commit suicide at a rate of almost 3x women in many countries;

PROC PRINT DATA=count_sex_binary_means; run;
*this part doesn't really make sense with # suicides as endpoint so feel free to ignore! ;
DATA suicide_binary_ODDS; SET count_sex_binary_means; 
WHERE _STAT_ = 'MEAN';
obs_prop=suicides_no;
ODDS= suicides_no/(1-suicides_no); 
LOGIT = LOG(ODDS);
RUN;
PROC PRINT DATA=suicide_binary_ODDS; 
VAR obs_prop ODDS LOGIT country sex; 
TITLE 'Observed Proportion, Odds, Log Odds (LOGITS)';
RUN;
